services:
  # Orion is the context broker
  orion:
    platform: linux/amd64
    image: quay.io/fiware/orion-ld:1.6.0
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
      - context
    networks:
      - default
    expose:
      - '1026'
    ports:
      - '1026:1026'
    command: -dbhost mongo-db -logLevel DEBUG -forwarding -mongocOnly
    healthcheck:
      test: curl --fail -s http://orion:1026/version || exit 1
      interval: 5s
#context
  context: 
    image: danny0117/aeros-context:1.0.0
    hostname: context
    container_name: context
    expose: 
      - '5051'
    ports:
      - '5051:5051'
    networks:
      - default

  mongo-db:
    image: mongo:6.0
    hostname: mongo-db
    container_name: db-mongo
    expose:
      - "27017"
    ports:
      - "27017:27017" # localhost:27017
    networks:
      - default
    volumes:
      - mongo-db:/data/db
      - mongo-config:/data/configdb
    healthcheck:
      test: ["CMD", "mongosh", "localhost:27017/test", "--quiet"]
      interval: 5s

volumes:
  mongo-db: ~         
  mongo-config: ~     
